version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80" #обрати внимание что здесь порт а экспоз у апп
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: .
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb